# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file '.\rts_kr.ui'
#
# Created by: PyQt5 UI code generator 5.14.1
#
# WARNING! All changes made in this file will be lost!


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(1465, 1180)
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap(".\\그림1.jpg"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        MainWindow.setWindowIcon(icon)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.line = QtWidgets.QFrame(self.centralwidget)
        self.line.setGeometry(QtCore.QRect(210, -20, 20, 451))
        self.line.setFrameShape(QtWidgets.QFrame.VLine)
        self.line.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line.setObjectName("line")
        self.kuf_frame = QtWidgets.QFrame(self.centralwidget)
        self.kuf_frame.setEnabled(True)
        self.kuf_frame.setGeometry(QtCore.QRect(250, 65, 491, 321))
        self.kuf_frame.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.kuf_frame.setFrameShadow(QtWidgets.QFrame.Raised)
        self.kuf_frame.setObjectName("kuf_frame")
        self.groupBox_2 = QtWidgets.QGroupBox(self.kuf_frame)
        self.groupBox_2.setGeometry(QtCore.QRect(20, 10, 104, 131))
        self.groupBox_2.setObjectName("groupBox_2")
        self.verticalLayout_2 = QtWidgets.QVBoxLayout(self.groupBox_2)
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.kuf_down = QtWidgets.QPushButton(self.groupBox_2)
        self.kuf_down.setObjectName("kuf_down")
        self.verticalLayout_2.addWidget(self.kuf_down)
        self.kuf_gold = QtWidgets.QPushButton(self.groupBox_2)
        self.kuf_gold.setObjectName("kuf_gold")
        self.verticalLayout_2.addWidget(self.kuf_gold)
        self.kuf_original = QtWidgets.QPushButton(self.groupBox_2)
        self.kuf_original.setObjectName("kuf_original")
        self.verticalLayout_2.addWidget(self.kuf_original)
        self.groupBox = QtWidgets.QGroupBox(self.kuf_frame)
        self.groupBox.setGeometry(QtCore.QRect(20, 150, 451, 111))
        self.groupBox.setObjectName("groupBox")
        self.kuf_update = QtWidgets.QPushButton(self.groupBox)
        self.kuf_update.setGeometry(QtCore.QRect(330, 14, 101, 91))
        self.kuf_update.setObjectName("kuf_update")
        self.kuf_myrace = QtWidgets.QComboBox(self.groupBox)
        self.kuf_myrace.setGeometry(QtCore.QRect(160, 20, 76, 22))
        self.kuf_myrace.setObjectName("kuf_myrace")
        self.kuf_myrace.addItem("")
        self.kuf_myrace.addItem("")
        self.kuf_myname = QtWidgets.QLineEdit(self.groupBox)
        self.kuf_myname.setGeometry(QtCore.QRect(60, 20, 91, 20))
        self.kuf_myname.setObjectName("kuf_myname")
        self.kuf_yourname = QtWidgets.QLineEdit(self.groupBox)
        self.kuf_yourname.setGeometry(QtCore.QRect(60, 50, 91, 20))
        self.kuf_yourname.setObjectName("kuf_yourname")
        self.kuf_yourace = QtWidgets.QComboBox(self.groupBox)
        self.kuf_yourace.setGeometry(QtCore.QRect(160, 50, 76, 22))
        self.kuf_yourace.setObjectName("kuf_yourace")
        self.kuf_yourace.addItem("")
        self.kuf_yourace.addItem("")
        self.label_2 = QtWidgets.QLabel(self.groupBox)
        self.label_2.setGeometry(QtCore.QRect(10, 50, 41, 21))
        self.label_2.setObjectName("label_2")
        self.label_3 = QtWidgets.QLabel(self.groupBox)
        self.label_3.setGeometry(QtCore.QRect(10, 20, 41, 21))
        self.label_3.setFrameShape(QtWidgets.QFrame.NoFrame)
        self.label_3.setObjectName("label_3")
        self.label_4 = QtWidgets.QLabel(self.groupBox)
        self.label_4.setGeometry(QtCore.QRect(10, 80, 41, 21))
        self.label_4.setObjectName("label_4")
        self.kuf_map = QtWidgets.QComboBox(self.groupBox)
        self.kuf_map.setGeometry(QtCore.QRect(70, 80, 166, 22))
        self.kuf_map.setObjectName("kuf_map")
        self.kuf_map.addItem("")
        self.kuf_map.addItem("")
        self.groupBox_7 = QtWidgets.QGroupBox(self.groupBox)
        self.groupBox_7.setGeometry(QtCore.QRect(250, 20, 67, 70))
        self.groupBox_7.setObjectName("groupBox_7")
        self.verticalLayout_4 = QtWidgets.QVBoxLayout(self.groupBox_7)
        self.verticalLayout_4.setObjectName("verticalLayout_4")
        self.kuf_win = QtWidgets.QRadioButton(self.groupBox_7)
        self.kuf_win.setTabletTracking(False)
        self.kuf_win.setChecked(True)
        self.kuf_win.setObjectName("kuf_win")
        self.verticalLayout_4.addWidget(self.kuf_win)
        self.kuf_lose = QtWidgets.QRadioButton(self.groupBox_7)
        self.kuf_lose.setObjectName("kuf_lose")
        self.verticalLayout_4.addWidget(self.kuf_lose)
        self.groupBox_3 = QtWidgets.QGroupBox(self.kuf_frame)
        self.groupBox_3.setGeometry(QtCore.QRect(130, 10, 341, 131))
        self.groupBox_3.setObjectName("groupBox_3")
        self.kuf_rank = QtWidgets.QPushButton(self.groupBox_3)
        self.kuf_rank.setGeometry(QtCore.QRect(10, 30, 71, 81))
        self.kuf_rank.setObjectName("kuf_rank")
        self.kuf_cafe = QtWidgets.QPushButton(self.groupBox_3)
        self.kuf_cafe.setGeometry(QtCore.QRect(170, 30, 75, 41))
        self.kuf_cafe.setObjectName("kuf_cafe")
        self.kuf_balance = QtWidgets.QPushButton(self.groupBox_3)
        self.kuf_balance.setGeometry(QtCore.QRect(250, 30, 71, 81))
        self.kuf_balance.setObjectName("kuf_balance")
        self.kuf_hnor = QtWidgets.QPushButton(self.groupBox_3)
        self.kuf_hnor.setGeometry(QtCore.QRect(90, 30, 71, 81))
        self.kuf_hnor.setFocusPolicy(QtCore.Qt.WheelFocus)
        self.kuf_hnor.setObjectName("kuf_hnor")
        self.kuf_kakao = QtWidgets.QPushButton(self.groupBox_3)
        self.kuf_kakao.setGeometry(QtCore.QRect(170, 72, 75, 39))
        self.kuf_kakao.setObjectName("kuf_kakao")
        self.kuf_start = QtWidgets.QPushButton(self.kuf_frame)
        self.kuf_start.setGeometry(QtCore.QRect(20, 270, 451, 41))
        icon1 = QtGui.QIcon()
        icon1.addPixmap(QtGui.QPixmap(".\\KingdomUnderFire_128.ico"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.kuf_start.setIcon(icon1)
        self.kuf_start.setIconSize(QtCore.QSize(30, 30))
        self.kuf_start.setObjectName("kuf_start")
        self.verticalLayoutWidget = QtWidgets.QWidget(self.centralwidget)
        self.verticalLayoutWidget.setGeometry(QtCore.QRect(20, 20, 181, 371))
        self.verticalLayoutWidget.setObjectName("verticalLayoutWidget")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.verticalLayoutWidget)
        self.verticalLayout.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout.setSpacing(6)
        self.verticalLayout.setObjectName("verticalLayout")
        self.kuf_menu_2 = QtWidgets.QPushButton(self.verticalLayoutWidget)
        self.kuf_menu_2.setEnabled(True)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.kuf_menu_2.sizePolicy().hasHeightForWidth())
        self.kuf_menu_2.setSizePolicy(sizePolicy)
        self.kuf_menu_2.setMaximumSize(QtCore.QSize(16777215, 16777215))
        self.kuf_menu_2.setTabletTracking(False)
        self.kuf_menu_2.setAutoFillBackground(False)
        self.kuf_menu_2.setIcon(icon)
        self.kuf_menu_2.setIconSize(QtCore.QSize(30, 30))
        self.kuf_menu_2.setObjectName("kuf_menu_2")
        self.verticalLayout.addWidget(self.kuf_menu_2)
        self.kuf_menu = QtWidgets.QPushButton(self.verticalLayoutWidget)
        self.kuf_menu.setEnabled(True)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.kuf_menu.sizePolicy().hasHeightForWidth())
        self.kuf_menu.setSizePolicy(sizePolicy)
        self.kuf_menu.setMaximumSize(QtCore.QSize(16777215, 16777215))
        self.kuf_menu.setTabletTracking(False)
        self.kuf_menu.setAutoFillBackground(False)
        self.kuf_menu.setIcon(icon1)
        self.kuf_menu.setIconSize(QtCore.QSize(30, 30))
        self.kuf_menu.setObjectName("kuf_menu")
        self.verticalLayout.addWidget(self.kuf_menu)
        self.jurassic_menu = QtWidgets.QPushButton(self.verticalLayoutWidget)
        icon2 = QtGui.QIcon()
        icon2.addPixmap(QtGui.QPixmap(".\\NoCD_TheRanker_1_101.ico"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.jurassic_menu.setIcon(icon2)
        self.jurassic_menu.setIconSize(QtCore.QSize(30, 30))
        self.jurassic_menu.setObjectName("jurassic_menu")
        self.verticalLayout.addWidget(self.jurassic_menu)
        self.imjinrok_menu = QtWidgets.QPushButton(self.verticalLayoutWidget)
        icon3 = QtGui.QIcon()
        icon3.addPixmap(QtGui.QPixmap(".\\뙉뷥_207.ico"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.imjinrok_menu.setIcon(icon3)
        self.imjinrok_menu.setIconSize(QtCore.QSize(30, 30))
        self.imjinrok_menu.setObjectName("imjinrok_menu")
        self.verticalLayout.addWidget(self.imjinrok_menu)
        self.newmyth_menu = QtWidgets.QPushButton(self.verticalLayoutWidget)
        icon4 = QtGui.QIcon()
        icon4.addPixmap(QtGui.QPixmap(".\\뙉뷥_1_207.ico"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.newmyth_menu.setIcon(icon4)
        self.newmyth_menu.setIconSize(QtCore.QSize(30, 30))
        self.newmyth_menu.setObjectName("newmyth_menu")
        self.verticalLayout.addWidget(self.newmyth_menu)
        self.mirrorwar_menu = QtWidgets.QPushButton(self.verticalLayoutWidget)
        icon5 = QtGui.QIcon()
        icon5.addPixmap(QtGui.QPixmap(".\\Mirror war_101.ico"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.mirrorwar_menu.setIcon(icon5)
        self.mirrorwar_menu.setIconSize(QtCore.QSize(30, 30))
        self.mirrorwar_menu.setObjectName("mirrorwar_menu")
        self.verticalLayout.addWidget(self.mirrorwar_menu)
        self.atrox_menu = QtWidgets.QPushButton(self.verticalLayoutWidget)
        self.atrox_menu.setEnabled(False)
        icon6 = QtGui.QIcon()
        icon6.addPixmap(QtGui.QPixmap(".\\Atrox_107.ico"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.atrox_menu.setIcon(icon6)
        self.atrox_menu.setIconSize(QtCore.QSize(30, 30))
        self.atrox_menu.setObjectName("atrox_menu")
        self.verticalLayout.addWidget(self.atrox_menu)
        self.imjinrok_frame = QtWidgets.QFrame(self.centralwidget)
        self.imjinrok_frame.setEnabled(True)
        self.imjinrok_frame.setGeometry(QtCore.QRect(780, 60, 491, 321))
        self.imjinrok_frame.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.imjinrok_frame.setFrameShadow(QtWidgets.QFrame.Raised)
        self.imjinrok_frame.setObjectName("imjinrok_frame")
        self.groupBox_4 = QtWidgets.QGroupBox(self.imjinrok_frame)
        self.groupBox_4.setGeometry(QtCore.QRect(20, 10, 104, 131))
        self.groupBox_4.setObjectName("groupBox_4")
        self.verticalLayout_3 = QtWidgets.QVBoxLayout(self.groupBox_4)
        self.verticalLayout_3.setObjectName("verticalLayout_3")
        self.imjinrok_down = QtWidgets.QPushButton(self.groupBox_4)
        self.imjinrok_down.setObjectName("imjinrok_down")
        self.verticalLayout_3.addWidget(self.imjinrok_down)
        self.imjinrok_path = QtWidgets.QPushButton(self.groupBox_4)
        self.imjinrok_path.setObjectName("imjinrok_path")
        self.verticalLayout_3.addWidget(self.imjinrok_path)
        self.imjinrok_eslpatch = QtWidgets.QPushButton(self.groupBox_4)
        self.imjinrok_eslpatch.setObjectName("imjinrok_eslpatch")
        self.verticalLayout_3.addWidget(self.imjinrok_eslpatch)
        self.imjinrok_jmpatch = QtWidgets.QPushButton(self.groupBox_4)
        self.imjinrok_jmpatch.setObjectName("imjinrok_jmpatch")
        self.verticalLayout_3.addWidget(self.imjinrok_jmpatch)
        self.groupBox_5 = QtWidgets.QGroupBox(self.imjinrok_frame)
        self.groupBox_5.setGeometry(QtCore.QRect(20, 150, 451, 111))
        self.groupBox_5.setObjectName("groupBox_5")
        self.imjinrok_update = QtWidgets.QPushButton(self.groupBox_5)
        self.imjinrok_update.setGeometry(QtCore.QRect(330, 14, 101, 91))
        self.imjinrok_update.setObjectName("imjinrok_update")
        self.imjinrok_myrace = QtWidgets.QComboBox(self.groupBox_5)
        self.imjinrok_myrace.setGeometry(QtCore.QRect(160, 20, 76, 22))
        self.imjinrok_myrace.setObjectName("imjinrok_myrace")
        self.imjinrok_myrace.addItem("")
        self.imjinrok_myrace.addItem("")
        self.imjinrok_myrace.addItem("")
        self.imjinrok_myname = QtWidgets.QLineEdit(self.groupBox_5)
        self.imjinrok_myname.setGeometry(QtCore.QRect(60, 20, 91, 20))
        self.imjinrok_myname.setObjectName("imjinrok_myname")
        self.imjinrok_yourname = QtWidgets.QLineEdit(self.groupBox_5)
        self.imjinrok_yourname.setGeometry(QtCore.QRect(60, 50, 91, 20))
        self.imjinrok_yourname.setObjectName("imjinrok_yourname")
        self.imjinrok_yourace = QtWidgets.QComboBox(self.groupBox_5)
        self.imjinrok_yourace.setGeometry(QtCore.QRect(160, 50, 76, 22))
        self.imjinrok_yourace.setObjectName("imjinrok_yourace")
        self.imjinrok_yourace.addItem("")
        self.imjinrok_yourace.addItem("")
        self.imjinrok_yourace.addItem("")
        self.label_6 = QtWidgets.QLabel(self.groupBox_5)
        self.label_6.setGeometry(QtCore.QRect(10, 50, 41, 21))
        self.label_6.setObjectName("label_6")
        self.label_7 = QtWidgets.QLabel(self.groupBox_5)
        self.label_7.setGeometry(QtCore.QRect(10, 20, 41, 21))
        self.label_7.setFrameShape(QtWidgets.QFrame.NoFrame)
        self.label_7.setObjectName("label_7")
        self.imjinrok_win = QtWidgets.QRadioButton(self.groupBox_5)
        self.imjinrok_win.setGeometry(QtCore.QRect(260, 30, 51, 21))
        self.imjinrok_win.setTabletTracking(False)
        self.imjinrok_win.setChecked(True)
        self.imjinrok_win.setObjectName("imjinrok_win")
        self.imjinrok_lose = QtWidgets.QRadioButton(self.groupBox_5)
        self.imjinrok_lose.setGeometry(QtCore.QRect(260, 60, 51, 21))
        self.imjinrok_lose.setObjectName("imjinrok_lose")
        self.label_8 = QtWidgets.QLabel(self.groupBox_5)
        self.label_8.setGeometry(QtCore.QRect(10, 80, 41, 21))
        self.label_8.setObjectName("label_8")
        self.imjinrok_map = QtWidgets.QComboBox(self.groupBox_5)
        self.imjinrok_map.setGeometry(QtCore.QRect(70, 80, 166, 22))
        self.imjinrok_map.setObjectName("imjinrok_map")
        self.imjinrok_map.addItem("")
        self.imjinrok_map.addItem("")
        self.groupBox_6 = QtWidgets.QGroupBox(self.imjinrok_frame)
        self.groupBox_6.setGeometry(QtCore.QRect(130, 10, 341, 131))
        self.groupBox_6.setObjectName("groupBox_6")
        self.imjinrok_rank = QtWidgets.QPushButton(self.groupBox_6)
        self.imjinrok_rank.setGeometry(QtCore.QRect(10, 30, 71, 81))
        self.imjinrok_rank.setObjectName("imjinrok_rank")
        self.imjinrok_cafe = QtWidgets.QPushButton(self.groupBox_6)
        self.imjinrok_cafe.setGeometry(QtCore.QRect(90, 30, 71, 81))
        self.imjinrok_cafe.setObjectName("imjinrok_cafe")
        self.imjinrok_skin = QtWidgets.QPushButton(self.groupBox_6)
        self.imjinrok_skin.setGeometry(QtCore.QRect(250, 30, 71, 81))
        self.imjinrok_skin.setObjectName("imjinrok_skin")
        self.imjinrok_kakao = QtWidgets.QPushButton(self.groupBox_6)
        self.imjinrok_kakao.setGeometry(QtCore.QRect(170, 28, 71, 81))
        self.imjinrok_kakao.setObjectName("imjinrok_kakao")
        self.imjinrok_start = QtWidgets.QPushButton(self.imjinrok_frame)
        self.imjinrok_start.setGeometry(QtCore.QRect(20, 270, 451, 41))
        self.imjinrok_start.setIcon(icon3)
        self.imjinrok_start.setIconSize(QtCore.QSize(30, 30))
        self.imjinrok_start.setObjectName("imjinrok_start")
        self.newmyth_frame = QtWidgets.QFrame(self.centralwidget)
        self.newmyth_frame.setEnabled(True)
        self.newmyth_frame.setGeometry(QtCore.QRect(250, 400, 491, 321))
        self.newmyth_frame.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.newmyth_frame.setFrameShadow(QtWidgets.QFrame.Raised)
        self.newmyth_frame.setObjectName("newmyth_frame")
        self.groupBox_10 = QtWidgets.QGroupBox(self.newmyth_frame)
        self.groupBox_10.setGeometry(QtCore.QRect(20, 10, 104, 131))
        self.groupBox_10.setObjectName("groupBox_10")
        self.verticalLayout_5 = QtWidgets.QVBoxLayout(self.groupBox_10)
        self.verticalLayout_5.setObjectName("verticalLayout_5")
        self.newmyth_down = QtWidgets.QPushButton(self.groupBox_10)
        self.newmyth_down.setObjectName("newmyth_down")
        self.verticalLayout_5.addWidget(self.newmyth_down)
        self.newmyth_path = QtWidgets.QPushButton(self.groupBox_10)
        self.newmyth_path.setObjectName("newmyth_path")
        self.verticalLayout_5.addWidget(self.newmyth_path)
        self.groupBox_11 = QtWidgets.QGroupBox(self.newmyth_frame)
        self.groupBox_11.setGeometry(QtCore.QRect(20, 150, 451, 111))
        self.groupBox_11.setObjectName("groupBox_11")
        self.newmyth_update = QtWidgets.QPushButton(self.groupBox_11)
        self.newmyth_update.setGeometry(QtCore.QRect(330, 14, 101, 91))
        self.newmyth_update.setObjectName("newmyth_update")
        self.newmyth_myrace = QtWidgets.QComboBox(self.groupBox_11)
        self.newmyth_myrace.setGeometry(QtCore.QRect(160, 20, 76, 22))
        self.newmyth_myrace.setObjectName("newmyth_myrace")
        self.newmyth_myrace.addItem("")
        self.newmyth_myrace.addItem("")
        self.newmyth_myrace.addItem("")
        self.newmyth_myname = QtWidgets.QLineEdit(self.groupBox_11)
        self.newmyth_myname.setGeometry(QtCore.QRect(60, 20, 91, 20))
        self.newmyth_myname.setObjectName("newmyth_myname")
        self.newmyth_yourname = QtWidgets.QLineEdit(self.groupBox_11)
        self.newmyth_yourname.setGeometry(QtCore.QRect(60, 50, 91, 20))
        self.newmyth_yourname.setObjectName("newmyth_yourname")
        self.newmyth_yourace = QtWidgets.QComboBox(self.groupBox_11)
        self.newmyth_yourace.setGeometry(QtCore.QRect(160, 50, 76, 22))
        self.newmyth_yourace.setObjectName("newmyth_yourace")
        self.newmyth_yourace.addItem("")
        self.newmyth_yourace.addItem("")
        self.newmyth_yourace.addItem("")
        self.label_14 = QtWidgets.QLabel(self.groupBox_11)
        self.label_14.setGeometry(QtCore.QRect(10, 50, 41, 21))
        self.label_14.setObjectName("label_14")
        self.label_15 = QtWidgets.QLabel(self.groupBox_11)
        self.label_15.setGeometry(QtCore.QRect(10, 20, 41, 21))
        self.label_15.setFrameShape(QtWidgets.QFrame.NoFrame)
        self.label_15.setObjectName("label_15")
        self.newmyth_win = QtWidgets.QRadioButton(self.groupBox_11)
        self.newmyth_win.setGeometry(QtCore.QRect(260, 30, 51, 21))
        self.newmyth_win.setTabletTracking(False)
        self.newmyth_win.setChecked(True)
        self.newmyth_win.setObjectName("newmyth_win")
        self.newmyth_lose = QtWidgets.QRadioButton(self.groupBox_11)
        self.newmyth_lose.setGeometry(QtCore.QRect(260, 60, 51, 21))
        self.newmyth_lose.setObjectName("newmyth_lose")
        self.label_16 = QtWidgets.QLabel(self.groupBox_11)
        self.label_16.setGeometry(QtCore.QRect(10, 80, 41, 21))
        self.label_16.setObjectName("label_16")
        self.newmyth_map = QtWidgets.QComboBox(self.groupBox_11)
        self.newmyth_map.setGeometry(QtCore.QRect(70, 80, 166, 22))
        self.newmyth_map.setObjectName("newmyth_map")
        self.newmyth_map.addItem("")
        self.newmyth_map.addItem("")
        self.groupBox_12 = QtWidgets.QGroupBox(self.newmyth_frame)
        self.groupBox_12.setGeometry(QtCore.QRect(130, 10, 341, 131))
        self.groupBox_12.setObjectName("groupBox_12")
        self.newmyth_rank = QtWidgets.QPushButton(self.groupBox_12)
        self.newmyth_rank.setGeometry(QtCore.QRect(10, 30, 91, 81))
        self.newmyth_rank.setObjectName("newmyth_rank")
        self.newmyth_kakao_2 = QtWidgets.QPushButton(self.groupBox_12)
        self.newmyth_kakao_2.setGeometry(QtCore.QRect(220, 30, 101, 81))
        self.newmyth_kakao_2.setObjectName("newmyth_kakao_2")
        self.newmyth_cafe = QtWidgets.QPushButton(self.groupBox_12)
        self.newmyth_cafe.setGeometry(QtCore.QRect(110, 30, 101, 81))
        self.newmyth_cafe.setObjectName("newmyth_cafe")
        self.newmyth_start = QtWidgets.QPushButton(self.newmyth_frame)
        self.newmyth_start.setGeometry(QtCore.QRect(20, 270, 451, 41))
        self.newmyth_start.setIcon(icon4)
        self.newmyth_start.setIconSize(QtCore.QSize(30, 30))
        self.newmyth_start.setObjectName("newmyth_start")
        self.mirror_frame = QtWidgets.QFrame(self.centralwidget)
        self.mirror_frame.setEnabled(True)
        self.mirror_frame.setGeometry(QtCore.QRect(780, 402, 491, 321))
        self.mirror_frame.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.mirror_frame.setFrameShadow(QtWidgets.QFrame.Raised)
        self.mirror_frame.setObjectName("mirror_frame")
        self.groupBox_13 = QtWidgets.QGroupBox(self.mirror_frame)
        self.groupBox_13.setGeometry(QtCore.QRect(20, 10, 104, 131))
        self.groupBox_13.setObjectName("groupBox_13")
        self.verticalLayout_6 = QtWidgets.QVBoxLayout(self.groupBox_13)
        self.verticalLayout_6.setObjectName("verticalLayout_6")
        self.mirrorwar_down = QtWidgets.QPushButton(self.groupBox_13)
        self.mirrorwar_down.setObjectName("mirrorwar_down")
        self.verticalLayout_6.addWidget(self.mirrorwar_down)
        self.mirrorwar_path = QtWidgets.QPushButton(self.groupBox_13)
        self.mirrorwar_path.setObjectName("mirrorwar_path")
        self.verticalLayout_6.addWidget(self.mirrorwar_path)
        self.groupBox_14 = QtWidgets.QGroupBox(self.mirror_frame)
        self.groupBox_14.setGeometry(QtCore.QRect(20, 150, 451, 111))
        self.groupBox_14.setObjectName("groupBox_14")
        self.mirrorwar_update = QtWidgets.QPushButton(self.groupBox_14)
        self.mirrorwar_update.setGeometry(QtCore.QRect(330, 14, 101, 91))
        self.mirrorwar_update.setObjectName("mirrorwar_update")
        self.mirrorwar_myrace = QtWidgets.QComboBox(self.groupBox_14)
        self.mirrorwar_myrace.setGeometry(QtCore.QRect(160, 20, 76, 22))
        self.mirrorwar_myrace.setObjectName("mirrorwar_myrace")
        self.mirrorwar_myrace.addItem("")
        self.mirrorwar_myrace.addItem("")
        self.mirrorwar_myrace.addItem("")
        self.mirrorwar_myname = QtWidgets.QLineEdit(self.groupBox_14)
        self.mirrorwar_myname.setGeometry(QtCore.QRect(60, 20, 91, 20))
        self.mirrorwar_myname.setObjectName("mirrorwar_myname")
        self.mirrorwar_yourname = QtWidgets.QLineEdit(self.groupBox_14)
        self.mirrorwar_yourname.setGeometry(QtCore.QRect(60, 50, 91, 20))
        self.mirrorwar_yourname.setObjectName("mirrorwar_yourname")
        self.mirrorwar_yourace = QtWidgets.QComboBox(self.groupBox_14)
        self.mirrorwar_yourace.setGeometry(QtCore.QRect(160, 50, 76, 22))
        self.mirrorwar_yourace.setObjectName("mirrorwar_yourace")
        self.mirrorwar_yourace.addItem("")
        self.mirrorwar_yourace.addItem("")
        self.mirrorwar_yourace.addItem("")
        self.label_18 = QtWidgets.QLabel(self.groupBox_14)
        self.label_18.setGeometry(QtCore.QRect(10, 50, 41, 21))
        self.label_18.setObjectName("label_18")
        self.label_19 = QtWidgets.QLabel(self.groupBox_14)
        self.label_19.setGeometry(QtCore.QRect(10, 20, 41, 21))
        self.label_19.setFrameShape(QtWidgets.QFrame.NoFrame)
        self.label_19.setObjectName("label_19")
        self.kuf_win_5 = QtWidgets.QRadioButton(self.groupBox_14)
        self.kuf_win_5.setGeometry(QtCore.QRect(260, 30, 51, 21))
        self.kuf_win_5.setTabletTracking(False)
        self.kuf_win_5.setChecked(True)
        self.kuf_win_5.setObjectName("kuf_win_5")
        self.kuf_lose_5 = QtWidgets.QRadioButton(self.groupBox_14)
        self.kuf_lose_5.setGeometry(QtCore.QRect(260, 60, 51, 21))
        self.kuf_lose_5.setObjectName("kuf_lose_5")
        self.label_20 = QtWidgets.QLabel(self.groupBox_14)
        self.label_20.setGeometry(QtCore.QRect(10, 80, 41, 21))
        self.label_20.setObjectName("label_20")
        self.mirrorwar_map = QtWidgets.QComboBox(self.groupBox_14)
        self.mirrorwar_map.setGeometry(QtCore.QRect(70, 80, 166, 22))
        self.mirrorwar_map.setObjectName("mirrorwar_map")
        self.mirrorwar_map.addItem("")
        self.mirrorwar_map.addItem("")
        self.groupBox_15 = QtWidgets.QGroupBox(self.mirror_frame)
        self.groupBox_15.setGeometry(QtCore.QRect(130, 10, 341, 131))
        self.groupBox_15.setObjectName("groupBox_15")
        self.mirrorwar_rank = QtWidgets.QPushButton(self.groupBox_15)
        self.mirrorwar_rank.setGeometry(QtCore.QRect(10, 30, 91, 81))
        self.mirrorwar_rank.setObjectName("mirrorwar_rank")
        self.mirrorwar_cafe = QtWidgets.QPushButton(self.groupBox_15)
        self.mirrorwar_cafe.setGeometry(QtCore.QRect(110, 30, 101, 81))
        self.mirrorwar_cafe.setObjectName("mirrorwar_cafe")
        self.mirrorwar_kakao = QtWidgets.QPushButton(self.groupBox_15)
        self.mirrorwar_kakao.setGeometry(QtCore.QRect(220, 30, 101, 81))
        self.mirrorwar_kakao.setObjectName("mirrorwar_kakao")
        self.mirrorwar_start = QtWidgets.QPushButton(self.mirror_frame)
        self.mirrorwar_start.setGeometry(QtCore.QRect(20, 270, 451, 41))
        self.mirrorwar_start.setIcon(icon5)
        self.mirrorwar_start.setIconSize(QtCore.QSize(30, 30))
        self.mirrorwar_start.setObjectName("mirrorwar_start")
        self.jurrasic_frame = QtWidgets.QFrame(self.centralwidget)
        self.jurrasic_frame.setEnabled(True)
        self.jurrasic_frame.setGeometry(QtCore.QRect(250, 760, 491, 321))
        self.jurrasic_frame.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.jurrasic_frame.setFrameShadow(QtWidgets.QFrame.Raised)
        self.jurrasic_frame.setObjectName("jurrasic_frame")
        self.groupBox_16 = QtWidgets.QGroupBox(self.jurrasic_frame)
        self.groupBox_16.setGeometry(QtCore.QRect(20, 10, 104, 131))
        self.groupBox_16.setObjectName("groupBox_16")
        self.verticalLayout_7 = QtWidgets.QVBoxLayout(self.groupBox_16)
        self.verticalLayout_7.setObjectName("verticalLayout_7")
        self.jurassic_down = QtWidgets.QPushButton(self.groupBox_16)
        self.jurassic_down.setObjectName("jurassic_down")
        self.verticalLayout_7.addWidget(self.jurassic_down)
        self.jurassic_path = QtWidgets.QPushButton(self.groupBox_16)
        self.jurassic_path.setObjectName("jurassic_path")
        self.verticalLayout_7.addWidget(self.jurassic_path)
        self.groupBox_17 = QtWidgets.QGroupBox(self.jurrasic_frame)
        self.groupBox_17.setGeometry(QtCore.QRect(20, 150, 451, 111))
        self.groupBox_17.setObjectName("groupBox_17")
        self.kuf_update_6 = QtWidgets.QPushButton(self.groupBox_17)
        self.kuf_update_6.setGeometry(QtCore.QRect(330, 14, 101, 91))
        self.kuf_update_6.setObjectName("kuf_update_6")
        self.kuf_myrace_6 = QtWidgets.QComboBox(self.groupBox_17)
        self.kuf_myrace_6.setGeometry(QtCore.QRect(160, 20, 76, 22))
        self.kuf_myrace_6.setObjectName("kuf_myrace_6")
        self.kuf_myrace_6.addItem("")
        self.kuf_myrace_6.addItem("")
        self.kuf_myrace_6.addItem("")
        self.kuf_myrace_6.addItem("")
        self.kuf_myname_6 = QtWidgets.QLineEdit(self.groupBox_17)
        self.kuf_myname_6.setGeometry(QtCore.QRect(60, 20, 91, 20))
        self.kuf_myname_6.setObjectName("kuf_myname_6")
        self.kuf_yourname_6 = QtWidgets.QLineEdit(self.groupBox_17)
        self.kuf_yourname_6.setGeometry(QtCore.QRect(60, 50, 91, 20))
        self.kuf_yourname_6.setObjectName("kuf_yourname_6")
        self.kuf_yourace_6 = QtWidgets.QComboBox(self.groupBox_17)
        self.kuf_yourace_6.setGeometry(QtCore.QRect(160, 50, 76, 22))
        self.kuf_yourace_6.setObjectName("kuf_yourace_6")
        self.kuf_yourace_6.addItem("")
        self.kuf_yourace_6.addItem("")
        self.kuf_yourace_6.addItem("")
        self.kuf_yourace_6.addItem("")
        self.label_22 = QtWidgets.QLabel(self.groupBox_17)
        self.label_22.setGeometry(QtCore.QRect(10, 50, 41, 21))
        self.label_22.setObjectName("label_22")
        self.label_23 = QtWidgets.QLabel(self.groupBox_17)
        self.label_23.setGeometry(QtCore.QRect(10, 20, 41, 21))
        self.label_23.setFrameShape(QtWidgets.QFrame.NoFrame)
        self.label_23.setObjectName("label_23")
        self.kuf_win_6 = QtWidgets.QRadioButton(self.groupBox_17)
        self.kuf_win_6.setGeometry(QtCore.QRect(260, 30, 51, 21))
        self.kuf_win_6.setTabletTracking(False)
        self.kuf_win_6.setChecked(True)
        self.kuf_win_6.setObjectName("kuf_win_6")
        self.kuf_lose_6 = QtWidgets.QRadioButton(self.groupBox_17)
        self.kuf_lose_6.setGeometry(QtCore.QRect(260, 60, 51, 21))
        self.kuf_lose_6.setObjectName("kuf_lose_6")
        self.label_24 = QtWidgets.QLabel(self.groupBox_17)
        self.label_24.setGeometry(QtCore.QRect(10, 80, 41, 21))
        self.label_24.setObjectName("label_24")
        self.kuf_map_6 = QtWidgets.QComboBox(self.groupBox_17)
        self.kuf_map_6.setGeometry(QtCore.QRect(70, 80, 166, 22))
        self.kuf_map_6.setObjectName("kuf_map_6")
        self.kuf_map_6.addItem("")
        self.kuf_map_6.addItem("")
        self.groupBox_18 = QtWidgets.QGroupBox(self.jurrasic_frame)
        self.groupBox_18.setGeometry(QtCore.QRect(130, 10, 341, 131))
        self.groupBox_18.setObjectName("groupBox_18")
        self.jurassic_rank = QtWidgets.QPushButton(self.groupBox_18)
        self.jurassic_rank.setGeometry(QtCore.QRect(10, 30, 71, 81))
        self.jurassic_rank.setObjectName("jurassic_rank")
        self.jurassic_cafe = QtWidgets.QPushButton(self.groupBox_18)
        self.jurassic_cafe.setGeometry(QtCore.QRect(170, 30, 75, 41))
        self.jurassic_cafe.setObjectName("jurassic_cafe")
        self.jurassic_balance = QtWidgets.QPushButton(self.groupBox_18)
        self.jurassic_balance.setGeometry(QtCore.QRect(250, 30, 71, 81))
        self.jurassic_balance.setObjectName("jurassic_balance")
        self.jurassic_hnor = QtWidgets.QPushButton(self.groupBox_18)
        self.jurassic_hnor.setGeometry(QtCore.QRect(90, 30, 71, 81))
        self.jurassic_hnor.setFocusPolicy(QtCore.Qt.WheelFocus)
        self.jurassic_hnor.setObjectName("jurassic_hnor")
        self.jurassic_kakao = QtWidgets.QPushButton(self.groupBox_18)
        self.jurassic_kakao.setGeometry(QtCore.QRect(170, 72, 75, 39))
        self.jurassic_kakao.setObjectName("jurassic_kakao")
        self.kuf_start_6 = QtWidgets.QPushButton(self.jurrasic_frame)
        self.kuf_start_6.setGeometry(QtCore.QRect(20, 270, 451, 41))
        self.kuf_start_6.setIcon(icon2)
        self.kuf_start_6.setIconSize(QtCore.QSize(30, 30))
        self.kuf_start_6.setObjectName("kuf_start_6")
        self.atrox_frame = QtWidgets.QFrame(self.centralwidget)
        self.atrox_frame.setEnabled(True)
        self.atrox_frame.setGeometry(QtCore.QRect(780, 760, 491, 321))
        self.atrox_frame.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.atrox_frame.setFrameShadow(QtWidgets.QFrame.Raised)
        self.atrox_frame.setObjectName("atrox_frame")
        self.groupBox_19 = QtWidgets.QGroupBox(self.atrox_frame)
        self.groupBox_19.setGeometry(QtCore.QRect(20, 10, 104, 131))
        self.groupBox_19.setObjectName("groupBox_19")
        self.verticalLayout_8 = QtWidgets.QVBoxLayout(self.groupBox_19)
        self.verticalLayout_8.setObjectName("verticalLayout_8")
        self.atrox_down = QtWidgets.QPushButton(self.groupBox_19)
        self.atrox_down.setObjectName("atrox_down")
        self.verticalLayout_8.addWidget(self.atrox_down)
        self.atrox_path = QtWidgets.QPushButton(self.groupBox_19)
        self.atrox_path.setObjectName("atrox_path")
        self.verticalLayout_8.addWidget(self.atrox_path)
        self.groupBox_20 = QtWidgets.QGroupBox(self.atrox_frame)
        self.groupBox_20.setGeometry(QtCore.QRect(20, 150, 451, 111))
        self.groupBox_20.setObjectName("groupBox_20")
        self.atrox_update = QtWidgets.QPushButton(self.groupBox_20)
        self.atrox_update.setGeometry(QtCore.QRect(330, 14, 101, 91))
        self.atrox_update.setObjectName("atrox_update")
        self.atrox_myrace = QtWidgets.QComboBox(self.groupBox_20)
        self.atrox_myrace.setGeometry(QtCore.QRect(160, 20, 76, 22))
        self.atrox_myrace.setObjectName("atrox_myrace")
        self.atrox_myrace.addItem("")
        self.atrox_myrace.addItem("")
        self.atrox_myrace.addItem("")
        self.atrox_myname = QtWidgets.QLineEdit(self.groupBox_20)
        self.atrox_myname.setGeometry(QtCore.QRect(60, 20, 91, 20))
        self.atrox_myname.setObjectName("atrox_myname")
        self.atrox_yourname = QtWidgets.QLineEdit(self.groupBox_20)
        self.atrox_yourname.setGeometry(QtCore.QRect(60, 50, 91, 20))
        self.atrox_yourname.setObjectName("atrox_yourname")
        self.atrox_yourace = QtWidgets.QComboBox(self.groupBox_20)
        self.atrox_yourace.setGeometry(QtCore.QRect(160, 50, 76, 22))
        self.atrox_yourace.setObjectName("atrox_yourace")
        self.atrox_yourace.addItem("")
        self.atrox_yourace.addItem("")
        self.atrox_yourace.addItem("")
        self.label_26 = QtWidgets.QLabel(self.groupBox_20)
        self.label_26.setGeometry(QtCore.QRect(10, 50, 41, 21))
        self.label_26.setObjectName("label_26")
        self.label_27 = QtWidgets.QLabel(self.groupBox_20)
        self.label_27.setGeometry(QtCore.QRect(10, 20, 41, 21))
        self.label_27.setFrameShape(QtWidgets.QFrame.NoFrame)
        self.label_27.setObjectName("label_27")
        self.atrox_win = QtWidgets.QRadioButton(self.groupBox_20)
        self.atrox_win.setGeometry(QtCore.QRect(260, 30, 51, 21))
        self.atrox_win.setTabletTracking(False)
        self.atrox_win.setChecked(True)
        self.atrox_win.setObjectName("atrox_win")
        self.atrox_lose = QtWidgets.QRadioButton(self.groupBox_20)
        self.atrox_lose.setGeometry(QtCore.QRect(260, 60, 51, 21))
        self.atrox_lose.setObjectName("atrox_lose")
        self.label_28 = QtWidgets.QLabel(self.groupBox_20)
        self.label_28.setGeometry(QtCore.QRect(10, 80, 41, 21))
        self.label_28.setObjectName("label_28")
        self.atrox_map = QtWidgets.QComboBox(self.groupBox_20)
        self.atrox_map.setGeometry(QtCore.QRect(70, 80, 166, 22))
        self.atrox_map.setObjectName("atrox_map")
        self.atrox_map.addItem("")
        self.atrox_map.addItem("")
        self.groupBox_21 = QtWidgets.QGroupBox(self.atrox_frame)
        self.groupBox_21.setGeometry(QtCore.QRect(130, 10, 341, 131))
        self.groupBox_21.setObjectName("groupBox_21")
        self.atrox_rank = QtWidgets.QPushButton(self.groupBox_21)
        self.atrox_rank.setGeometry(QtCore.QRect(10, 30, 71, 81))
        self.atrox_rank.setObjectName("atrox_rank")
        self.atrox_cafe = QtWidgets.QPushButton(self.groupBox_21)
        self.atrox_cafe.setGeometry(QtCore.QRect(84, 30, 161, 41))
        self.atrox_cafe.setObjectName("atrox_cafe")
        self.atrox_balance = QtWidgets.QPushButton(self.groupBox_21)
        self.atrox_balance.setGeometry(QtCore.QRect(250, 30, 71, 81))
        self.atrox_balance.setObjectName("atrox_balance")
        self.atrox_kakao = QtWidgets.QPushButton(self.groupBox_21)
        self.atrox_kakao.setGeometry(QtCore.QRect(84, 72, 161, 39))
        self.atrox_kakao.setObjectName("atrox_kakao")
        self.atrox_start = QtWidgets.QPushButton(self.atrox_frame)
        self.atrox_start.setGeometry(QtCore.QRect(20, 270, 451, 41))
        self.atrox_start.setIcon(icon6)
        self.atrox_start.setIconSize(QtCore.QSize(30, 30))
        self.atrox_start.setObjectName("atrox_start")
        self.lineEdit = QtWidgets.QLineEdit(self.centralwidget)
        self.lineEdit.setGeometry(QtCore.QRect(510, 40, 113, 20))
        self.lineEdit.setObjectName("lineEdit")
        self.kuf_ip_2 = QtWidgets.QLabel(self.centralwidget)
        self.kuf_ip_2.setGeometry(QtCore.QRect(640, 40, 81, 21))
        self.kuf_ip_2.setFrameShape(QtWidgets.QFrame.NoFrame)
        self.kuf_ip_2.setObjectName("kuf_ip_2")
        self.kuf_ip_4 = QtWidgets.QLabel(self.centralwidget)
        self.kuf_ip_4.setGeometry(QtCore.QRect(470, 40, 41, 21))
        self.kuf_ip_4.setFrameShape(QtWidgets.QFrame.NoFrame)
        self.kuf_ip_4.setObjectName("kuf_ip_4")
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 1465, 21))
        self.menubar.setObjectName("menubar")
        self.menu = QtWidgets.QMenu(self.menubar)
        self.menu.setObjectName("menu")
        self.menu_2 = QtWidgets.QMenu(self.menubar)
        self.menu_2.setObjectName("menu_2")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)
        self.launcherexit_action = QtWidgets.QAction(MainWindow)
        self.launcherexit_action.setObjectName("launcherexit_action")
        self.launcherinfo_action = QtWidgets.QAction(MainWindow)
        self.launcherinfo_action.setObjectName("launcherinfo_action")
        self.nikanme_action = QtWidgets.QAction(MainWindow)
        self.nikanme_action.setObjectName("nikanme_action")
        self.laucherupdate_action = QtWidgets.QAction(MainWindow)
        self.laucherupdate_action.setObjectName("laucherupdate_action")
        self.menu.addAction(self.nikanme_action)
        self.menu.addAction(self.launcherexit_action)
        self.menu_2.addAction(self.laucherupdate_action)
        self.menu_2.addAction(self.launcherinfo_action)
        self.menubar.addAction(self.menu.menuAction())
        self.menubar.addAction(self.menu_2.menuAction())

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)
        MainWindow.setTabOrder(self.kuf_menu, self.jurassic_menu)
        MainWindow.setTabOrder(self.jurassic_menu, self.imjinrok_menu)
        MainWindow.setTabOrder(self.imjinrok_menu, self.newmyth_menu)
        MainWindow.setTabOrder(self.newmyth_menu, self.mirrorwar_menu)
        MainWindow.setTabOrder(self.mirrorwar_menu, self.atrox_menu)
        MainWindow.setTabOrder(self.atrox_menu, self.kuf_yourname)
        MainWindow.setTabOrder(self.kuf_yourname, self.kuf_yourace)
        MainWindow.setTabOrder(self.kuf_yourace, self.kuf_win)
        MainWindow.setTabOrder(self.kuf_win, self.kuf_lose)
        MainWindow.setTabOrder(self.kuf_lose, self.kuf_map)
        MainWindow.setTabOrder(self.kuf_map, self.kuf_rank)
        MainWindow.setTabOrder(self.kuf_rank, self.kuf_cafe)
        MainWindow.setTabOrder(self.kuf_cafe, self.kuf_balance)
        MainWindow.setTabOrder(self.kuf_balance, self.kuf_hnor)
        MainWindow.setTabOrder(self.kuf_hnor, self.kuf_kakao)
        MainWindow.setTabOrder(self.kuf_kakao, self.kuf_start)
        MainWindow.setTabOrder(self.kuf_start, self.kuf_down)
        MainWindow.setTabOrder(self.kuf_down, self.kuf_gold)
        MainWindow.setTabOrder(self.kuf_gold, self.kuf_original)
        MainWindow.setTabOrder(self.kuf_original, self.kuf_update)
        MainWindow.setTabOrder(self.kuf_update, self.kuf_myrace)
        MainWindow.setTabOrder(self.kuf_myrace, self.kuf_myname)

        def PRINTVV():
                if self.kuf_win.isChecked :
                        print("win")
                else :
                        print("lose")


        self.kuf_update.clicked.connect(PRINTVV)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "RTS.KR_1.00"))
        self.groupBox_2.setTitle(_translate("MainWindow", "다운로드&& 패치"))
        self.kuf_down.setText(_translate("MainWindow", "다운로드"))
        self.kuf_gold.setText(_translate("MainWindow", "골드패치"))
        self.kuf_original.setText(_translate("MainWindow", "오리지널 패치"))
        self.groupBox.setTitle(_translate("MainWindow", "전적 업데이트"))
        self.kuf_update.setText(_translate("MainWindow", "업데이트"))
        self.kuf_myrace.setItemText(0, _translate("MainWindow", "휴먼"))
        self.kuf_myrace.setItemText(1, _translate("MainWindow", "데빌"))
        self.kuf_yourace.setItemText(0, _translate("MainWindow", "휴먼"))
        self.kuf_yourace.setItemText(1, _translate("MainWindow", "데빌"))
        self.label_2.setText(_translate("MainWindow", "상대방"))
        self.label_3.setText(_translate("MainWindow", "나"))
        self.label_4.setText(_translate("MainWindow", "대전맵"))
        self.kuf_map.setItemText(0, _translate("MainWindow", "타우크로스"))
        self.kuf_map.setItemText(1, _translate("MainWindow", "데스티네이션"))
        self.groupBox_7.setTitle(_translate("MainWindow", "승패"))
        self.kuf_win.setText(_translate("MainWindow", "승리"))
        self.kuf_lose.setText(_translate("MainWindow", "패배"))
        self.groupBox_3.setTitle(_translate("MainWindow", "웹 사이트"))
        self.kuf_rank.setText(_translate("MainWindow", "전적기록실"))
        self.kuf_cafe.setText(_translate("MainWindow", "커뮤니티"))
        self.kuf_balance.setText(_translate("MainWindow", "유닛 상성표"))
        self.kuf_hnor.setText(_translate("MainWindow", "명예전당\n"
"자료실"))
        self.kuf_kakao.setText(_translate("MainWindow", "카카오톡\n"
"오픈채팅방"))
        self.kuf_start.setText(_translate("MainWindow", "KUF 게임실행"))
        self.kuf_menu_2.setText(_translate("MainWindow", "서네떡의 전략시뮬이션"))
        self.kuf_menu.setText(_translate("MainWindow", "킹덤언더파이어"))
        self.jurassic_menu.setText(_translate("MainWindow", "쥬라기원시전2:더랭커"))
        self.imjinrok_menu.setText(_translate("MainWindow", "임진록2+:조선의반격"))
        self.newmyth_menu.setText(_translate("MainWindow", "신 천년의신화"))
        self.mirrorwar_menu.setText(_translate("MainWindow", "거울전쟁:은의여인"))
        self.atrox_menu.setText(_translate("MainWindow", "아트록스"))
        self.groupBox_4.setTitle(_translate("MainWindow", "다운로드&& 패치"))
        self.imjinrok_down.setText(_translate("MainWindow", "다운로드"))
        self.imjinrok_path.setText(_translate("MainWindow", "실행 경로설정"))
        self.imjinrok_eslpatch.setText(_translate("MainWindow", "ESL1.4패치"))
        self.imjinrok_jmpatch.setText(_translate("MainWindow", "JM 1.8패치"))
        self.groupBox_5.setTitle(_translate("MainWindow", "전적 업데이트"))
        self.imjinrok_update.setText(_translate("MainWindow", "업데이트"))
        self.imjinrok_myrace.setItemText(0, _translate("MainWindow", "조선"))
        self.imjinrok_myrace.setItemText(1, _translate("MainWindow", "일본"))
        self.imjinrok_myrace.setItemText(2, _translate("MainWindow", "명"))
        self.imjinrok_yourace.setItemText(0, _translate("MainWindow", "조선"))
        self.imjinrok_yourace.setItemText(1, _translate("MainWindow", "일본"))
        self.imjinrok_yourace.setItemText(2, _translate("MainWindow", "명"))
        self.label_6.setText(_translate("MainWindow", "상대방"))
        self.label_7.setText(_translate("MainWindow", "나"))
        self.imjinrok_win.setText(_translate("MainWindow", "승리"))
        self.imjinrok_lose.setText(_translate("MainWindow", "패배"))
        self.label_8.setText(_translate("MainWindow", "대전맵"))
        self.imjinrok_map.setItemText(0, _translate("MainWindow", "타우크로스"))
        self.imjinrok_map.setItemText(1, _translate("MainWindow", "데스티네이션"))
        self.groupBox_6.setTitle(_translate("MainWindow", "웹 사이트"))
        self.imjinrok_rank.setText(_translate("MainWindow", "전적기록실"))
        self.imjinrok_cafe.setText(_translate("MainWindow", "커뮤니티"))
        self.imjinrok_skin.setText(_translate("MainWindow", "임진록 스킨\n"
"다운로드"))
        self.imjinrok_kakao.setText(_translate("MainWindow", "카카오톡\n"
"오픈채팅방"))
        self.imjinrok_start.setText(_translate("MainWindow", "임진록2+조선의반격 게임실행"))
        self.groupBox_10.setTitle(_translate("MainWindow", "다운로드&& 패치"))
        self.newmyth_down.setText(_translate("MainWindow", "다운로드"))
        self.newmyth_path.setText(_translate("MainWindow", "실행 경로설정"))
        self.groupBox_11.setTitle(_translate("MainWindow", "전적 업데이트"))
        self.newmyth_update.setText(_translate("MainWindow", "업데이트"))
        self.newmyth_myrace.setItemText(0, _translate("MainWindow", "고구려"))
        self.newmyth_myrace.setItemText(1, _translate("MainWindow", "백제"))
        self.newmyth_myrace.setItemText(2, _translate("MainWindow", "신라"))
        self.newmyth_yourace.setItemText(0, _translate("MainWindow", "고구려"))
        self.newmyth_yourace.setItemText(1, _translate("MainWindow", "백제"))
        self.newmyth_yourace.setItemText(2, _translate("MainWindow", "신라"))
        self.label_14.setText(_translate("MainWindow", "상대방"))
        self.label_15.setText(_translate("MainWindow", "나"))
        self.newmyth_win.setText(_translate("MainWindow", "승리"))
        self.newmyth_lose.setText(_translate("MainWindow", "패배"))
        self.label_16.setText(_translate("MainWindow", "대전맵"))
        self.newmyth_map.setItemText(0, _translate("MainWindow", "타우크로스"))
        self.newmyth_map.setItemText(1, _translate("MainWindow", "데스티네이션"))
        self.groupBox_12.setTitle(_translate("MainWindow", "웹 사이트"))
        self.newmyth_rank.setText(_translate("MainWindow", "전적기록실"))
        self.newmyth_kakao_2.setText(_translate("MainWindow", "카카오톡\n"
"오픈채팅방"))
        self.newmyth_cafe.setText(_translate("MainWindow", "커뮤니티"))
        self.newmyth_start.setText(_translate("MainWindow", "신 천년의신화 게임실행"))
        self.groupBox_13.setTitle(_translate("MainWindow", "다운로드&& 패치"))
        self.mirrorwar_down.setText(_translate("MainWindow", "다운로드"))
        self.mirrorwar_path.setText(_translate("MainWindow", "실행 경로설정"))
        self.groupBox_14.setTitle(_translate("MainWindow", "전적 업데이트"))
        self.mirrorwar_update.setText(_translate("MainWindow", "업데이트"))
        self.mirrorwar_myrace.setItemText(0, _translate("MainWindow", "해방군"))
        self.mirrorwar_myrace.setItemText(1, _translate("MainWindow", "악령군"))
        self.mirrorwar_myrace.setItemText(2, _translate("MainWindow", "흑마술파"))
        self.mirrorwar_yourace.setItemText(0, _translate("MainWindow", "해방군"))
        self.mirrorwar_yourace.setItemText(1, _translate("MainWindow", "악령군"))
        self.mirrorwar_yourace.setItemText(2, _translate("MainWindow", "흑마술파"))
        self.label_18.setText(_translate("MainWindow", "상대방"))
        self.label_19.setText(_translate("MainWindow", "나"))
        self.kuf_win_5.setText(_translate("MainWindow", "승리"))
        self.kuf_lose_5.setText(_translate("MainWindow", "패배"))
        self.label_20.setText(_translate("MainWindow", "대전맵"))
        self.mirrorwar_map.setItemText(0, _translate("MainWindow", "타우크로스"))
        self.mirrorwar_map.setItemText(1, _translate("MainWindow", "데스티네이션"))
        self.groupBox_15.setTitle(_translate("MainWindow", "웹 사이트"))
        self.mirrorwar_rank.setText(_translate("MainWindow", "전적기록실"))
        self.mirrorwar_cafe.setText(_translate("MainWindow", "커뮤니티"))
        self.mirrorwar_kakao.setText(_translate("MainWindow", "카카오톡\n"
"오픈채팅방"))
        self.mirrorwar_start.setText(_translate("MainWindow", "거울전쟁:은의여인 게임실행"))
        self.groupBox_16.setTitle(_translate("MainWindow", "다운로드&& 패치"))
        self.jurassic_down.setText(_translate("MainWindow", "다운로드"))
        self.jurassic_path.setText(_translate("MainWindow", "실행 경로설정"))
        self.groupBox_17.setTitle(_translate("MainWindow", "전적 업데이트"))
        self.kuf_update_6.setText(_translate("MainWindow", "업데이트"))
        self.kuf_myrace_6.setItemText(0, _translate("MainWindow", "원시인"))
        self.kuf_myrace_6.setItemText(1, _translate("MainWindow", "티라노"))
        self.kuf_myrace_6.setItemText(2, _translate("MainWindow", "엘프"))
        self.kuf_myrace_6.setItemText(3, _translate("MainWindow", "데몬"))
        self.kuf_yourace_6.setItemText(0, _translate("MainWindow", "원시인"))
        self.kuf_yourace_6.setItemText(1, _translate("MainWindow", "티라노"))
        self.kuf_yourace_6.setItemText(2, _translate("MainWindow", "엘프"))
        self.kuf_yourace_6.setItemText(3, _translate("MainWindow", "데몬"))
        self.label_22.setText(_translate("MainWindow", "상대방"))
        self.label_23.setText(_translate("MainWindow", "나"))
        self.kuf_win_6.setText(_translate("MainWindow", "승리"))
        self.kuf_lose_6.setText(_translate("MainWindow", "패배"))
        self.label_24.setText(_translate("MainWindow", "대전맵"))
        self.kuf_map_6.setItemText(0, _translate("MainWindow", "타우크로스"))
        self.kuf_map_6.setItemText(1, _translate("MainWindow", "데스티네이션"))
        self.groupBox_18.setTitle(_translate("MainWindow", "웹 사이트"))
        self.jurassic_rank.setText(_translate("MainWindow", "전적기록실"))
        self.jurassic_cafe.setText(_translate("MainWindow", "커뮤니티"))
        self.jurassic_balance.setText(_translate("MainWindow", "유닛 상성표"))
        self.jurassic_hnor.setText(_translate("MainWindow", "명예전당"))
        self.jurassic_kakao.setText(_translate("MainWindow", "카카오톡\n"
"오픈채팅방"))
        self.kuf_start_6.setText(_translate("MainWindow", "쥬라기원시전2:더랭커 게임실행"))
        self.groupBox_19.setTitle(_translate("MainWindow", "다운로드&& 패치"))
        self.atrox_down.setText(_translate("MainWindow", "다운로드"))
        self.atrox_path.setText(_translate("MainWindow", "실행 경로설정"))
        self.groupBox_20.setTitle(_translate("MainWindow", "전적 업데이트"))
        self.atrox_update.setText(_translate("MainWindow", "업데이트"))
        self.atrox_myrace.setItemText(0, _translate("MainWindow", "호미니언"))
        self.atrox_myrace.setItemText(1, _translate("MainWindow", "인텔리언"))
        self.atrox_myrace.setItemText(2, _translate("MainWindow", "크리티스"))
        self.atrox_yourace.setItemText(0, _translate("MainWindow", "호미니언"))
        self.atrox_yourace.setItemText(1, _translate("MainWindow", "인텔리언"))
        self.atrox_yourace.setItemText(2, _translate("MainWindow", "크리티스"))
        self.label_26.setText(_translate("MainWindow", "상대방"))
        self.label_27.setText(_translate("MainWindow", "나"))
        self.atrox_win.setText(_translate("MainWindow", "승리"))
        self.atrox_lose.setText(_translate("MainWindow", "패배"))
        self.label_28.setText(_translate("MainWindow", "대전맵"))
        self.atrox_map.setItemText(0, _translate("MainWindow", "타우크로스"))
        self.atrox_map.setItemText(1, _translate("MainWindow", "데스티네이션"))
        self.groupBox_21.setTitle(_translate("MainWindow", "웹 사이트"))
        self.atrox_rank.setText(_translate("MainWindow", "전적기록실"))
        self.atrox_cafe.setText(_translate("MainWindow", "커뮤니티"))
        self.atrox_balance.setText(_translate("MainWindow", "유닛 상성표"))
        self.atrox_kakao.setText(_translate("MainWindow", "카카오톡\n"
"오픈채팅방"))
        self.atrox_start.setText(_translate("MainWindow", "아트록스 게임실행"))
        self.kuf_ip_2.setText(_translate("MainWindow", "25.266.222.222"))
        self.kuf_ip_4.setText(_translate("MainWindow", "닉네임"))
        self.menu.setTitle(_translate("MainWindow", "설정"))
        self.menu_2.setTitle(_translate("MainWindow", "기타"))
        self.launcherexit_action.setText(_translate("MainWindow", "종료"))
        self.launcherinfo_action.setText(_translate("MainWindow", "프로그램 정보"))
        self.nikanme_action.setText(_translate("MainWindow", "닉네임 설정"))
        self.laucherupdate_action.setText(_translate("MainWindow", "업데이트 확인"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    MainWindow = QtWidgets.QMainWindow()
    ui = Ui_MainWindow()
    ui.setupUi(MainWindow)
    MainWindow.show()
    sys.exit(app.exec_())
